name: .NET Core CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Build Docker image
      run: |
        docker build -t dedalus-task .

    - name: Create required directories
      run: |
        docker run --rm -v /home/runner/work/dedalus/dedalus:/app -w /app dedalus-task /bin/bash -c "mkdir -p /var/opt/dedalus/userdata/bin /var/opt/dedalus/userdata/charts/beta/validations /var/opt/dedalus/userdata/ci /var/opt/dedalus/userdata/postgres/data/logs /var/opt/dedalus/userdata/script /var/opt/dedalus/userdata/templates"

    - name: Run Docker container
      run: |
        docker run --rm -e DIRECTORY_PATH="/var/opt/dedalus/userdata" dedalus-task
